### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by SmashinFries** [yandex-research/vqdm#4]
The examples `quantization.sh` and `metric_calculation.sh` are not in the repo

**Comment by Godofnothing** [comment]
Hi, @SmashinFries.


The proposed method is architecture agnostic, so, in principle, it works with any modern diffusion model. Given that the FLUX model is much larger, the benefits from its compression are more pronounced. However, the current implementation is focused towards SDXL-like architectures and adding support for FLUX would require significant effort. We hope to produce VQDM quantized FLUX models in the future.

**Comment by Vahe1994** [comment]
Hi, @SmashinFries!
Thank you for noticing. We forgot to add them in the commit.  We will add them soon.
